@startuml

allowmixing

node attack
node fight
node movement

class PlayerManager << (S,#FF7700) Singleton >> {
  +float energy
  +float cooldown
  +void CardPlayed(gameobject troopPrefab)
}

class GameManager << (S,#FF7700) Singleton >> {

}

class AudioManager {
  +PlaySound()
  +PlayMusic()
}

class SoundManager << (U,#bababa) Unity >> {}

class SpawnManager {
  +SpawnPoint Spawnpoints
  +void Spawn(GameObject troopPrefab, int lane, bool isLeftPlayer)
  +GenerateSpawnPoints(string player, Vector3 offset)
  +GetSpawnPoint(int lane, bool isLeftPlayer)
}


class TroopManager {
  +List<TroopHandler> troops
  +AttackTroop()
  +AttackPhase()
}

class TroopHandler {
  +flaot health
  +TakeDamage()
  +Death()
}

class Melee {
  +attackRange
  +attackDamage
  +attackSpeed
  +Attack()
}

class Ranged {
  +attackRange
  +attackDamage
  +attackSpeed
  +Shoot()
}

class RangePoint {
  +EnemyInRange
  +UpdateRangeCollider()
}

class StraightMovement {
  +float movementSpeed
}

class DeckManager? {}
class HandManager? {} 

class CardManager {
  +CreateCard
  +PlayCard()
}

class Card {
  +int lane
  +Troop troopPrefab
}

class HealthBar {
  +Slider slider
  +ChangeHealth()
  +SetMaximumHealth()
}

actor Player

Player -> PlayerManager
Player -> Card

Card ..> CardManager
CardManager ..> PlayerManager
PlayerManager ..> GameManager

GameManager -- SpawnManager
GameManager -- AudioManager
GameManager -- TroopManager

SpawnManager <..> PlayerManager : GetSpawnPoint()
SpawnManager ..> TroopHandler : Spawn
AudioManager ..> SoundManager

TroopHandler ..> TroopManager : DealDamage

TroopHandler .. fight
TroopHandler .. movement
TroopHandler ..> HealthBar

fight .. Melee
fight .. Ranged

movement .. StraightMovement

Melee <.. RangePoint
Ranged <.. RangePoint

Melee ..> attack
Ranged ..> attack


attack --> TroopManager

@enduml
